on: [push]

jobs:
  call_composite_action:
    runs-on: ubuntu-latest
    name: A job use reusable action
    steps:
      - uses: ./.github/my_actions/sub-routine-action@master@sandbox/new_pr3
      - id: call_sub_routine
        with:
          input-data: 'my input data!'
      - run: echo results is ${{ steps.call_sub_routine.outputs.output-data }}
        shell: bash
